spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      mode: always
  datasource:
     url: jdbc:mysql://localhost:3306/football
     username: springstudent
     password: springstudent