spring:
  application:
    name: GatewayServer
  cloud:
    gateway:
      routes:
        - id: players
          uri: lb://FootballServer
          predicates:
            - Path=/api/players/**
          filters:
            - StripPrefix=1
        - id: albums
          uri: lb://AlbumsServer
          predicates:
            - Path=/api/albums/**
          filters:
            - StripPrefix=1
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/